language: "ko-KR"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false # 코드래빗이 리뷰 끝나면 알아서 PR 승인하게끔
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
