// app/layout.tsx
import "./globals.css";
import MainLayout from "../components/MainLayout";

export const metadata = {
  title: "My App",
  description: "Generated by ChatGPT",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="font-paperlogy">
        {/* 모바일 고정 컨테이너 */}
        <div className="min-h-screen bg-gray-100 flex justify-center">
          <div
            className="w-full bg-white relative overflow-hidden"
            style={{
              maxWidth: "600px",
              minHeight: "100vh",
              boxShadow: "0 0 20px rgba(0,0,0,0.1)",
            }}
          >
            <MainLayout>{children}</MainLayout>
          </div>
        </div>
      </body>
    </html>
  );
}
