import "./globals.css";

export const metadata = {
  title: "My App",
  description: "Generated by ChatGPT",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="font-paperlogy">{children}</body>
    </html>
  );
}
